version: "3.7"
services:
  db:
    image: mysql:5.7.30
    command: --default-authentication-plugin=mysql_native_password --explicit_defaults_for_timestamp
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: "commentsDb"
      MYSQL_ROOT_PASSWORD: strongDbPass

  redis:
    image: redis
    command: redis-server --requirepass Redis2019!
    ports:
      - "6379:6379"

  api:
    build: .
    restart: always
    depends_on:
      - db
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - DB_HOST=db # this should be identical to the database service name
      - DB_USER=root
      - DB_DATABASE=commentsDb
      - DB_PASSWORD=strongDbPass
      - TOKEN_SECRET=QA3GCPvnNO3e6x29dFfzbvIlP8pRNwif # don't forget to change this
