
CREATE TABLE IF NOT EXISTS comments (
    id int(11) NOT NULL AUTO_INCREMENT,
    post int(11) NOT NULL,
    comment_text text NOT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;